name: CI

on:
  push:
    branches:
      - new-format

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019]

    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        ref: new-format
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        architecture: 'x64'
    - name: install deps
      run: python -m pip install -r requirements-build-exe.txt
    - name: build release
      run: python cx_setup.py build
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: wt-tools_${{ matrix.os }}
        path: build/
